In [1]:
# teste movimentação formigas 

In [2]:
import numpy as np
import random as rn

In [3]:
direcoes = ['N','S','L','O']

In [4]:
def direcao():
    return direcoes[rn.randint(0,3)]      

In [15]:
posicao = np.random.randint(2, size=(10,10))
copia = posicao.copy() 
i = rn.randint(0,len(posicao)-1)
j = rn.randint(0,len(posicao)-1)

#anterior = posicao[i][j] 
#posicao[i][j] = 22

#fazzer uma copia da matrix posicao 
#posicao[i][j] = copia[i][j]

print(posicao)

dir = direcao()
for k in range(len(posicao)+10):
    aux = rn.randint(1,100)
   
    #print(dir,aux)

    if (aux%2 == 0):
        dir = direcao() 
    
    print(dir)
    print(i,j)      
    #anterior = posicao[i][j]
    if (dir == 'N' and i+1 < len(posicao)):    
        posicao[i][j] = copia[i][j]  
        i = i+1       
    elif (dir == 'S' and i-1 > 0):
        posicao[i][j] = copia[i][j]
        i=i-1        
    elif (dir == 'L' and j+1 < len(posicao)):
        posicao[i][j] = copia[i][j]
        j=j+1        
    elif (dir == 'O' and j-1 > 0):
        posicao[i][j] = copia[i][j]
        j=j-1        
    posicao[i][j] = 22

    print("\n",posicao)




[[0 0 0 0 1 1 0 0 0 0]
 [1 1 0 1 1 1 0 1 0 1]
 [1 0 0 0 1 1 1 1 0 0]
 [1 0 1 0 1 1 1 1 1 1]
 [1 0 0 0 1 1 0 1 1 0]
 [1 1 0 0 0 1 1 0 0 0]
 [0 0 0 0 1 1 0 1 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [0 1 0 0 1 1 1 0 1 1]
 [1 0 1 0 1 0 1 0 1 0]]
N
3 3

 [[ 0  0  0  0  1  1  0  0  0  0]
 [ 1  1  0  1  1  1  0  1  0  1]
 [ 1  0  0  0  1  1  1  1  0  0]
 [ 1  0  1  0  1  1  1  1  1  1]
 [ 1  0  0 22  1  1  0  1  1  0]
 [ 1  1  0  0  0  1  1  0  0  0]
 [ 0  0  0  0  1  1  0  1  0  1]
 [ 1  0  0  0  0  0  0  0  0  1]
 [ 0  1  0  0  1  1  1  0  1  1]
 [ 1  0  1  0  1  0  1  0  1  0]]
S
4 3

 [[ 0  0  0  0  1  1  0  0  0  0]
 [ 1  1  0  1  1  1  0  1  0  1]
 [ 1  0  0  0  1  1  1  1  0  0]
 [ 1  0  1 22  1  1  1  1  1  1]
 [ 1  0  0  0  1  1  0  1  1  0]
 [ 1  1  0  0  0  1  1  0  0  0]
 [ 0  0  0  0  1  1  0  1  0  1]
 [ 1  0  0  0  0  0  0  0  0  1]
 [ 0  1  0  0  1  1  1  0  1  1]
 [ 1  0  1  0  1  0  1  0  1  0]]
S
3 3

 [[ 0  0  0  0  1  1  0  0  0  0]
 [ 1  1  0  1  1  1  0  1  0  1]
 [ 1  0  0 22  1 